### ISSUE TITLE
Why not modify on mCalendar repo?

### ISSUE THREAD

**Issue by SpongeBobSun** [oong/OCR_ADDON#1]
Hi there,

I've noticed you started this new repo which based on mCalendar. I'm wondering instead start a new repo, why not modify the source code in your forked mCalendar repo? So that you can open a pull request for me and I can merge your code easily.

If you are using mCalendar as a plugin of your app, that's cool. Just don't forget to add my LICENSE file and my `github username` on your project's readme file.

One more thing is, icons in this project is from https://icons8.com/ . So don't forget add their license too if you are still using those icons.

Thanks.
Bob.

**Comment by oong** [comment]
Hi.

I`m so sorry for my misstake.
Because i'm not good at using GitHub, i don`t know about LICENSE.
What should i do for your and https://icon8.com's LICENSE? 
very very sorry!!

**Comment by SpongeBobSun** [comment]
Hi there,
No need to apologies - it's fine that you using my code. 
About the license file - when you fork my repo, it's already in there as long as you do not delete it manually.
About icon8.com license - check this link https://icons8.com/license/
You should add my name and icon8.com's link to your README file.
Enjoy the code !

Thanks.
Bob.

**Comment by oong** [comment]
OK! Thanks!!! 
I'll do that right now!

**Comment by SpongeBobSun** [comment]
You are welcome~
